name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the sender Docker image
        run: |
            docker login --username AliBaktash1 --password ghp_uLZr3Ae6OhZO
            docker build . --tag ghcr.io/AliBaktash1/devopsproject/tree/main/sender:latest
            docker push ghcr.io/AliBaktash1/devopsproject/tree/main/sender:latest
      - name: build reciever-image-2
        run: |
            docker login --username AliBaktash1 --password ghp_uLZr3Ae6OhZO
            docker build . --tag ghcr.io/AliBaktash1/devopsproject/tree/main/reciever:latest
            docker push ghcr.io/AliBaktash1/devopsproject/tree/main/reciever:latest