name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: AliBaktash1
password: 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
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/AliBaktash1/devopsproject/tree/main/sender:latest
       docker run ghcr.io/AliBaktash1/devopsproject/tree/main/sender:latest
       docker push ghcr.io/AliBaktash1/devopsproject/tree/main/sender:latest
run: |
       docker build . --tag ghcr.io/AliBaktash1/devopsproject/tree/main/reciever:latest
       docker run ghcr.io/AliBaktash1/devopsproject/tree/main/reciever:latest
       docker push ghcr.io/AliBaktash1/devopsproject/tree/main/reciever:latest
